version: '2.0'
services:
  web:
    build: .
    #ports:
    # - "8080:8080"
    expose:
      - "8080"
    #depends_on:
    # - nginx
    volumes:
      - .:/code
  lb:
    image: 'dockercloud/haproxy:latest'
    links:
      - web
    ports:
     - '8080:80'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
